services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DBMS_CONNECTION=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - DBMS_USERNAME=${POSTGRES_USER}
      - DBMS_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  db:
    image: postgres:18.3-alpine3.23
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db_data: